### Send POST request with json body
POST http://localhost:11001/v1/orders
Content-Type: application/json

{
  "metadata": {"id": "1234571", "source": "manu", "type": "mine", "dataContentType": "onetype", "subject": "order", "timestamp": "2022-05-26T08:14:26.543Z"},
  "orderId": "12349",
  "customerId": "54321",
  "orderDate": "2022-05-26T08:15:24.456Z",
  "orderLines": [
    {"lineId": "765433", "productId": "456765", "quantity": 2.34, "unitPrice": 5.34},
    {"lineId": "765435", "productId": "2345", "quantity": 1.0, "unitPrice": 15.80}
  ]
}
